import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Image from "next/image"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Pokedex",
    description: "Generated by create next app",
}

const ROUTES = [
    { path: "/pokemon", name: "Pokemon" },
    { path: "/type", name: "Types" },
    { path: "/species", name: "Species" },
]

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} bg-slate-200 scroll-smooth min-h-screen flex flex-col mx-4 sm:mx-36`}
            >
                <header className="p-5 flex items-center gap-6 border-b-2 border-slate-300">
                    <Link className="flex gap-2 items-center mr-auto" href="/">
                        <Image
                            className="h-8 w-auto"
                            src="/pokeball.svg"
                            alt="Pokeball Logo"
                            width={0}
                            height={0}
                            priority
                        />
                        <h1 className="font-bold text-lg">Pokedex</h1>
                    </Link>
                    {ROUTES.map(({ path, name }) => (
                        <Link
                            key={name}
                            href={path}
                            className="hover:underline hover:underline-offset-2"
                        >
                            {name}
                        </Link>
                    ))}
                </header>
                {children}
            </body>
        </html>
    )
}
